import subprocess
import threading
import multiprocessing as mp
import crashes

class Runner():
    def __init__(self, binary, mutator, ctx):
        self.binary = binary
        self.mutator = mutator
        self.ctx = ctx

        self.stop_event = ctx.Event()
        self.crash_condition = threading.Condition()
        self.crash_handler = crashes.CrashHandler(binary, self.crash_condition)
        self.crash_thread = threading.Thread(target=self.crash_handler.start)

        self.proc = None

    # loop to run the binary with inputs generated by the mutator
    def runner_loop(self):
        while not self.stop_event.is_set():
            with self.mutator.condition:
                # if there is no available inputs, sleep
                while not self.mutator.input_queue and not self.stop_event.is_set():
                    self.mutator.condition.wait()

                # if program has shut down, break out of loop
                if self.stop_event.is_set():
                    break

                input = self.mutator.input_queue.pop(0)

            try:
                # run the binary with the given input
                res = subprocess.run(self.binary, input=input, timeout=2.0)
                # if there is a crash, add it to the crash handlers queue
                if res.returncode != 0:
                    with self.crash_condition:
                        self.crash_handler.crashes.append({"result": res, "input": input, "type": "fail"})
                        self.crash_condition.notify()
            except subprocess.TimeoutExpired:
                # if there is a timeout, add it to the crash handlers queue
                with self.crash_condition:
                    self.crash_handler.crashes.append({"result": res, "input": input, "type": "timeout"})
                    self.crash_condition.notify()

    # starts the crash handler thread and runner loop process
    def start(self):
        # start crash handler thread
        self.crash_thread.start()

        # start runner process
        self.proc = self.ctx.Process(target=self.runner_loop)
        self.proc.start()

        # start inputs generator
        self.mutator.start()

    # terminates all running threads/processes associated with this runner
    def stop(self):
        self.stop_event.set()

        # stop crash worker thread
        self.crash_handler.running = False
        with self.crash_condition:
            self.crash_condition.notify()

        self.crash_thread.join()

        # stop process runner
        if self.proc:
            self.proc.terminate()
